# Generated by Django 4.1 on 2022-08-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Description',
            new_name='Descripcion',
        ),
    ]
